const foodData = [
  {
    name: "Margherita Pizza",
    description: "Classic pizza topped with mozzarella cheese and tomato sauce.",
    price: 299,
    category: "Pizza",
    image: "/images/margherita-pizza.png",
    rating: 4.7,
  },
  {
    name: "Veg Supreme Pizza",
    description: "Loaded with fresh vegetables and mozzarella cheese.",
    price: 399,
    category: "Pizza",
    image: "/images/veg-supreme-pizza.png",
    rating: 4.8,
  },
  {
    name: "Classic Veg Burger",
    description: "Soft bun with crispy vegetable patty and fresh veggies.",
    price: 179,
    category: "Burger",
    image: "/images/classic-veg-burger.png",
    rating: 4.5,
  },
  {
    name: "Loaded Cheese Burger",
    description: "Crispy veg patty loaded with melted cheese.",
    price: 229,
    category: "Burger",
    image: "/images/loaded-cheese-burger.png",
    rating: 4.7,
  },
  {
    name: "Creamy Alfredo Pasta",
    description: "Creamy white sauce pasta with herbs and vegetables.",
    price: 249,
    category: "Pasta",
    image: "/images/creamy-alfredo-pasta.png",
    rating: 4.6,
  },
  {
    name: "Arrabbiata Pasta",
    description: "Spicy Italian pasta cooked in rich tomato sauce.",
    price: 229,
    category: "Pasta",
    image: "/images/arrabbiata-pasta.png",
    rating: 4.5,
  },
  {
    name: "Spicy Hakka Noodles",
    description: "Chinese-style noodles tossed with vegetables.",
    price: 199,
    category: "Chinese",
    image: "/images/spicy-hakka-noodles.png",
    rating: 4.6,
  },
  {
    name: "Signature Veg Fried Rice",
    description: "Flavorful fried rice with fresh vegetables.",
    price: 189,
    category: "Chinese",
    image: "/images/signature-veg-fried-rice.png",
    rating: 4.5,
  },
  {
    name: "Veg Manchurian",
    description: "Crispy vegetable balls tossed in spicy Manchurian sauce.",
    price: 219,
    category: "Chinese",
    image: "/images/veg-manchurian.png",
    rating: 4.7,
  },
  {
    name: "Masala Dosa",
    description: "Crispy dosa served with potato masala and chutneys.",
    price: 149,
    category: "South Indian",
    image: "/images/masala-dosa.png",
    rating: 4.8,
  },
  {
    name: "Idli Sambar",
    description: "Soft idlis served with hot sambar and chutney.",
    price: 99,
    category: "South Indian",
    image: "/images/idli-sambar.png",
    rating: 4.7,
  },
  {
    name: "Poori Bhaji",
    description: "Fluffy pooris served with spicy potato curry.",
    price: 139,
    category: "South Indian",
    image: "/images/poori-bhaji.png",
    rating: 4.6,
  },
  {
    name: "Royal Paneer Biryani",
    description: "Aromatic basmati rice cooked with paneer and spices.",
    price: 289,
    category: "Biryani",
    image: "/images/royal-paneer-biryani.png",
    rating: 4.8,
  },
  {
    name: "Veg Thali",
    description: "Complete Indian meal with rice, curry, dal and roti.",
    price: 249,
    category: "Meals",
    image: "/images/veg-thali.png",
    rating: 4.8,
  },
  {
    name: "Garlic Bread",
    description: "Freshly baked garlic bread with herbs and butter.",
    price: 129,
    category: "Snacks",
    image: "/images/garlic-bread.png",
    rating: 4.5,
  },
  {
    name: "French Fries",
    description: "Golden crispy fries served with ketchup.",
    price: 129,
    category: "Snacks",
    image: "/images/french-fries.png",
    rating: 4.5,
  },
  {
    name: "Hot Chocolate Brownie",
    description: "Warm chocolate brownie served with rich chocolate sauce.",
    price: 149,
    category: "Dessert",
    image: "/images/hot-chocolate-brownie.png",
    rating: 4.8,
  },
  {
    name: "Vanilla Ice Cream",
    description: "Creamy vanilla ice cream made with premium milk.",
    price: 99,
    category: "Dessert",
    image: "/images/vanilla-ice-cream.png",
    rating: 4.6,
  },
  {
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice.",
    price: 119,
    category: "Drinks",
    image: "/images/fresh-orange-juice.png",
    rating: 4.7,
  },
  {
    name: "Iced Mocha Coffee",
    description: "Refreshing iced mocha topped with chocolate drizzle.",
    price: 169,
    category: "Drinks",
    image: "/images/iced-mocha-coffee.png",
    rating: 4.8,
  },
];

module.exports = foodData;
